# Generated by Django 5.1.7 on 2025-03-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Comments',
        ),
    ]
