# Generated by Django 5.1.7 on 2025-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Blogger', 'blogger'), ('Viewer', 'viewer')], default='Viewer', max_length=50),
        ),
    ]
