# Generated by Django 5.1.7 on 2025-03-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Likes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Relevant_links',
        ),
    ]
