# Generated by Django 5.1.7 on 2025-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_likes_remove_blog_relevant_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
